session_name: language-tools
start_directory: ./ # load session relative to config location (project root).
shell_command_before:
  - source ${PYTHON_ENV_DIR}/anki-language-tools/bin/activate
  - source .bash_aliases
  - source ${SECRETS_DIR}/anki_languagetools/tests.sh
  - source ${SECRETS_DIR}/anki_languagetools/clt_tts_prod.sh
  - source ${SECRETS_DIR}/anki_languagetools/clt_tts_vocabai_prod.sh
  - clear
windows:
- window_name: language-tools
  focus: true
- window_name: git
- window_name: aider
- window_name: log
  panes:
    - shell_command: tail -f ${HOME}/logs/languagetools.log
- window_name: secrets
  panes:
    - shell_command: 
      - cd ${SECRETS_DIR}/anki_languagetools
      - clear

